work_dir: ./work_dir

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: true
  random_move: true
  window_size: 150
  data_path: ./data/Kinetics/Kinetics/kinetics-skeleton/train_data.npy
  label_path: ./data/Kinetics/Kinetics/kinetics-skeleton/train_label.pkl
test_feeder_args:
  data_path: ./data/Kinetics/Kinetics/kinetics-skeleton/val_data.npy
  label_path: ./data/Kinetics/Kinetics/kinetics-skeleton/val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 1
  edge_importance_weighting: true
  graph_args:
    layout: openpose
    strategy: spatial

# training
device: [0]
batch_size: 4
test_batch_size: 32

#optim
base_lr: 0.1
step: [20, 30, 40, 50]
num_epoch: 2



